<Project Sdk="Microsoft.NET.Sdk">  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CoreEssentials</RootNamespace>
    <PackageId>CoreEssentials-MonoGame</PackageId>
    <Version>0.12.3</Version>
    <Authors>Michael Mena</Authors>
    <Company>LeoTheLegion</Company>
    <PackageDescription>A jump start for monogame dev</PackageDescription>
    <RepositoryUrl>https://github.com/LeoTheLegion/core-essentials-monogame</RepositoryUrl>
    <!-- XML Documentation Generation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\CoreEssentials.xml</DocumentationFile>
    <!-- Including Documentation in NuGet Package -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <!-- Debug symbol and SourceLink configuration -->
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EmbedAllSources>true</EmbedAllSources> <!-- Embeds all sources into the PDB. Alternatively, rely on SourceLink to fetch from repo. -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Aether.Physics2D.Diagnostics.MG" Version="2.1.1" />
    <PackageReference Include="Aether.Physics2D.MG" Version="2.1.1" />
    <PackageReference Include="MonoGame.Extended" Version="4.0.2" />
    <PackageReference Include="Myra" Version="1.5.5" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>  <ItemGroup>
    <Folder Include="src\Coroutines\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="CoreEssentials_Tests" DependsOnTargets="Build">
    <Exec Command="dotnet test ..\CoreEssentials.Tests\CoreEssentials.Tests.csproj" />
  </Target>
  <Target Name="CoreEssentials_Tests:rebuild" DependsOnTargets="Rebuild">
    <Exec Command="dotnet test ..\CoreEssentials.Tests\CoreEssentials.Tests.csproj" />
  </Target>
</Project>