using System;
using System.Globalization;
using System.IO;
using System.Linq;
using Microsoft.Xna.Framework;
using System.Xml.Linq;
using Xunit;
using CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem;
using CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Serialization;

namespace CoreEssentials.Tests.GameSystems.EntitySystems.EntityOOPsystem.Serialization
{
    public class PhysicsSceneSerializationTests
    {
private class PhysicsTestEntity : Entity
{
}

        private static EntitySystem NewSystemWithPrefab()
        {
            var system = new EntitySystem();
            system.RegisterPrefab("phys", EntityPrefabLoader.LoadFromXml(
                "<Prefab Type=\"PhysicsTestEntity\"><Components>" +
                "<Component Type=\"TransformSaveComponent\" /></Components></Prefab>"));
            return system;
        }

        [Fact]
        public void SaveLoad_Entities_WithExplicitIds_PreservesState()
        {
            // Arrange
            var system = NewSystemWithPrefab();
            
            // Create entities with explicit IDs (as done in PhysicsEntityScene)
            var entity1 = system.Instantiate("phys", Vector2.Zero);
            entity1.SetId("ball_10_100");
            entity1.Position = new Vector2(10, 100);
            entity1.Rotation = 0.5f;
            entity1.SetSort(1);
            
            var entity2 = system.Instantiate("phys", Vector2.Zero);
            entity2.SetId("vip_ball_640_360");
            entity2.Position = new Vector2(640, 360);
            entity2.Rotation = 1.2f;
            entity2.SetSort(2);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act - Save
                GameStateSerializer.SaveState(system, tempFile);
                
                // Load into new system
                var newSystem = NewSystemWithPrefab();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                var loadedEntity1 = entities.FirstOrDefault(e => e.Id == "ball_10_100");
                Assert.NotNull(loadedEntity1);
                Assert.Equal(new Vector2(10, 100), loadedEntity1.Position);
                Assert.Equal(0.5f, loadedEntity1.Rotation, 0.01f);
                
                var loadedEntity2 = entities.FirstOrDefault(e => e.Id == "vip_ball_640_360");
                Assert.NotNull(loadedEntity2);
                Assert.Equal(new Vector2(640, 360), loadedEntity2.Position);
                Assert.Equal(1.2f, loadedEntity2.Rotation, 0.01f);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void SaveState_AllEntitiesHaveAutoGeneratedIds()
        {
            // Arrange - All entities now have auto-generated IDs on creation
            var system = NewSystemWithPrefab();
            
            var entity1 = system.Instantiate("phys", new Vector2(10, 100));
            // ID is auto-generated by CreateEntity
            
            var entity2 = system.Instantiate("phys", Vector2.Zero);
            entity2.SetId("ball_with_id");
            entity2.Position = new Vector2(20, 200);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act
                GameStateSerializer.SaveState(system, tempFile);
                var xml = File.ReadAllText(tempFile);
                
                // Assert - Both entities should be in XML since they both have IDs
                Assert.Contains("ball_with_id", xml);
                Assert.Contains("TestEntity_", xml); // Auto-generated ID pattern
                
                // Verify by loading
                var newSystem = NewSystemWithPrefab();
                GameStateSerializer.LoadState(newSystem, tempFile);
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void SaveLoad_WithAutoGeneratedIds_PreservesEntities()
        {
            // Arrange - Test with auto-generated IDs
            var system = NewSystemWithPrefab();
            
            var entity1 = system.Instantiate("phys", new Vector2(10, 100));
            // No explicit ID - should auto-generate on EnsureId
            entity1.Position = new Vector2(10, 100);
            
            // Force ID generation by setting a dummy ID that triggers EnsureId
            // Since EnsureId is internal, we use reflection to test this
            var entityType = typeof(CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Entity);
            var ensureIdMethod = entityType.GetMethod("EnsureId", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var id1 = (string)ensureIdMethod.Invoke(entity1, null);
            Assert.NotNull(id1);
            
            var entity2 = system.Instantiate("phys", Vector2.Zero);
            var id2 = (string)ensureIdMethod.Invoke(entity2, null);
            entity2.Position = new Vector2(20, 200);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act
                GameStateSerializer.SaveState(system, tempFile);
                
                // Load into new system
                var newSystem = NewSystemWithPrefab();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                // Both entities should be loaded with their auto-generated IDs
                Assert.Contains(entities, e => e.Id == id1);
                Assert.Contains(entities, e => e.Id == id2);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void EndToEnd_EntitySceneSimulation()
        {
            // Arrange - Simulate scene creation
            var system = NewSystemWithPrefab();
            
            // Simulate creating entities like PhysicsEntityScene does
            // But without explicit IDs to test auto-generation
            var entity1 = system.Instantiate("phys", new Vector2(10, 100));
            
            var entity2 = system.Instantiate("phys", new Vector2(20, 200));
            
            // Force ID generation using reflection
            var entityType = typeof(CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Entity);
            var ensureIdMethod = entityType.GetMethod("EnsureId", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var id1 = (string)ensureIdMethod.Invoke(entity1, null);
            var id2 = (string)ensureIdMethod.Invoke(entity2, null);
            
            entity1.Rotation = 0.5f;
            entity2.Rotation = 1.2f;
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act - Save scene state
                GameStateSerializer.SaveState(system, tempFile);
                
                // Verify file contains entities
                var xml = File.ReadAllText(tempFile);
                Assert.Contains(id1, xml);
                Assert.Contains(id2, xml);
                
                // Load into new system
                var newSystem = NewSystemWithPrefab();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                var loadedEntity1 = entities.FirstOrDefault(e => e.Id == id1);
                Assert.NotNull(loadedEntity1);
                Assert.Equal(new Vector2(10, 100), loadedEntity1.Position);
                Assert.Equal(0.5f, loadedEntity1.Rotation, 0.01f);
                
                var loadedEntity2 = entities.FirstOrDefault(e => e.Id == id2);
                Assert.NotNull(loadedEntity2);
                Assert.Equal(new Vector2(20, 200), loadedEntity2.Position);
                Assert.Equal(1.2f, loadedEntity2.Rotation, 0.01f);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }
    }
}
