using System;
using System.Globalization;
using System.IO;
using System.Linq;
using Microsoft.Xna.Framework;
using System.Xml.Linq;
using Xunit;
using CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem;
using CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Serialization;

namespace CoreEssentials.Tests.GameSystems.EntitySystems.EntityOOPsystem.Serialization
{
    public class PhysicsSceneSerializationTests
    {
private class TestEntity : Entity, ISaveableEntity
{
    public XElement SaveState()
    {
        return new XElement("Entity",
            new XAttribute("Id", Id ?? string.Empty),
            new XAttribute("Type", GetType().FullName),
            new XAttribute("Rotation", Rotation.ToString(CultureInfo.InvariantCulture)),
            new XAttribute("Sort", GetSort()),
            new XAttribute("Active", GetActive()),
            new XElement("Position",
                new XAttribute("X", Position.X.ToString(CultureInfo.InvariantCulture)),
                new XAttribute("Y", Position.Y.ToString(CultureInfo.InvariantCulture))
            ),
            new XElement("Scale",
                new XAttribute("X", Scale.X.ToString(CultureInfo.InvariantCulture)),
                new XAttribute("Y", Scale.Y.ToString(CultureInfo.InvariantCulture))
            ),
            new XElement("Tags",
                Tags.Select(tag => new XElement("Tag", new XAttribute("Name", tag)))
            ));
    }

    public void LoadState(XElement element)
    {
        var pos = element.Element("Position");
        if (pos != null)
            Position = new Vector2(float.Parse(pos.Attribute("X")?.Value ?? "0", CultureInfo.InvariantCulture),
                float.Parse(pos.Attribute("Y")?.Value ?? "0", CultureInfo.InvariantCulture));

        if (float.TryParse(element.Attribute("Rotation")?.Value, NumberStyles.Any, CultureInfo.InvariantCulture, out var rot))
            Rotation = rot;

        var sc = element.Element("Scale");
        if (sc != null)
            Scale = new Vector2(float.Parse(sc.Attribute("X")?.Value ?? "1", CultureInfo.InvariantCulture),
                float.Parse(sc.Attribute("Y")?.Value ?? "1", CultureInfo.InvariantCulture));

        if (int.TryParse(element.Attribute("Sort")?.Value, NumberStyles.Any, CultureInfo.InvariantCulture, out var sort))
            SetSort(sort);

        if (bool.TryParse(element.Attribute("Active")?.Value, out var active))
            SetActive(active);

        foreach (var t in Tags.ToList()) RemoveTag(t);
        var tagsEl = element.Element("Tags");
        if (tagsEl != null)
            foreach (var tag in tagsEl.Elements("Tag"))
                SetTag(tag.Attribute("Name")?.Value ?? "default");
    }
        }

        [Fact]
        public void SaveLoad_Entities_WithExplicitIds_PreservesState()
        {
            // Arrange
            var system = new EntitySystem();
            
            // Create entities with explicit IDs (as done in PhysicsEntityScene)
            var entity1 = system.CreateEntity<TestEntity>();
            entity1.SetId("ball_10_100");
            entity1.Position = new Vector2(10, 100);
            entity1.Rotation = 0.5f;
            entity1.SetSort(1);
            
            var entity2 = system.CreateEntity<TestEntity>();
            entity2.SetId("vip_ball_640_360");
            entity2.Position = new Vector2(640, 360);
            entity2.Rotation = 1.2f;
            entity2.SetSort(2);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act - Save
                GameStateSerializer.SaveState(system, tempFile);
                
                // Load into new system
                var newSystem = new EntitySystem();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                var loadedEntity1 = entities.FirstOrDefault(e => e.Id == "ball_10_100");
                Assert.NotNull(loadedEntity1);
                Assert.Equal(new Vector2(10, 100), loadedEntity1.Position);
                Assert.Equal(0.5f, loadedEntity1.Rotation, 0.01f);
                
                var loadedEntity2 = entities.FirstOrDefault(e => e.Id == "vip_ball_640_360");
                Assert.NotNull(loadedEntity2);
                Assert.Equal(new Vector2(640, 360), loadedEntity2.Position);
                Assert.Equal(1.2f, loadedEntity2.Rotation, 0.01f);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void SaveState_AllEntitiesHaveAutoGeneratedIds()
        {
            // Arrange - All entities now have auto-generated IDs on creation
            var system = new EntitySystem();
            
            var entity1 = system.CreateEntity<TestEntity>();
            entity1.Position = new Vector2(10, 100);
            // ID is auto-generated by CreateEntity
            
            var entity2 = system.CreateEntity<TestEntity>();
            entity2.SetId("ball_with_id");
            entity2.Position = new Vector2(20, 200);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act
                GameStateSerializer.SaveState(system, tempFile);
                var xml = File.ReadAllText(tempFile);
                
                // Assert - Both entities should be in XML since they both have IDs
                Assert.Contains("ball_with_id", xml);
                Assert.Contains("TestEntity_", xml); // Auto-generated ID pattern
                
                // Verify by loading
                var newSystem = new EntitySystem();
                GameStateSerializer.LoadState(newSystem, tempFile);
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void SaveLoad_WithAutoGeneratedIds_PreservesEntities()
        {
            // Arrange - Test with auto-generated IDs
            var system = new EntitySystem();
            
            var entity1 = system.CreateEntity<TestEntity>();
            // No explicit ID - should auto-generate on EnsureId
            entity1.Position = new Vector2(10, 100);
            
            // Force ID generation by setting a dummy ID that triggers EnsureId
            // Since EnsureId is internal, we use reflection to test this
            var entityType = typeof(CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Entity);
            var ensureIdMethod = entityType.GetMethod("EnsureId", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var id1 = (string)ensureIdMethod.Invoke(entity1, null);
            Assert.NotNull(id1);
            
            var entity2 = system.CreateEntity<TestEntity>();
            var id2 = (string)ensureIdMethod.Invoke(entity2, null);
            entity2.Position = new Vector2(20, 200);
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act
                GameStateSerializer.SaveState(system, tempFile);
                
                // Load into new system
                var newSystem = new EntitySystem();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                // Both entities should be loaded with their auto-generated IDs
                Assert.Contains(entities, e => e.Id == id1);
                Assert.Contains(entities, e => e.Id == id2);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Fact]
        public void EndToEnd_EntitySceneSimulation()
        {
            // Arrange - Simulate scene creation
            var system = new EntitySystem();
            
            // Simulate creating entities like PhysicsEntityScene does
            // But without explicit IDs to test auto-generation
            var entity1 = system.CreateEntity<TestEntity>();
            entity1.Position = new Vector2(10, 100);
            
            var entity2 = system.CreateEntity<TestEntity>();
            entity2.Position = new Vector2(20, 200);
            
            // Force ID generation using reflection
            var entityType = typeof(CoreEssentials.GameSystems.EntitySystems.EntityOOPSystem.Entity);
            var ensureIdMethod = entityType.GetMethod("EnsureId", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var id1 = (string)ensureIdMethod.Invoke(entity1, null);
            var id2 = (string)ensureIdMethod.Invoke(entity2, null);
            
            entity1.Rotation = 0.5f;
            entity2.Rotation = 1.2f;
            
            var tempFile = Path.GetTempFileName();
            
            try
            {
                // Act - Save scene state
                GameStateSerializer.SaveState(system, tempFile);
                
                // Verify file contains entities
                var xml = File.ReadAllText(tempFile);
                Assert.Contains(id1, xml);
                Assert.Contains(id2, xml);
                
                // Load into new system
                var newSystem = new EntitySystem();
                GameStateSerializer.LoadState(newSystem, tempFile);
                
                // Assert
                var entities = newSystem.GetEntities();
                Assert.Equal(2, entities.Count);
                
                var loadedEntity1 = entities.FirstOrDefault(e => e.Id == id1);
                Assert.NotNull(loadedEntity1);
                Assert.Equal(new Vector2(10, 100), loadedEntity1.Position);
                Assert.Equal(0.5f, loadedEntity1.Rotation, 0.01f);
                
                var loadedEntity2 = entities.FirstOrDefault(e => e.Id == id2);
                Assert.NotNull(loadedEntity2);
                Assert.Equal(new Vector2(20, 200), loadedEntity2.Position);
                Assert.Equal(1.2f, loadedEntity2.Rotation, 0.01f);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }
    }
}
